
<?php /** @var \Mageplaza\Seo\Block\Richsnippets\Organization $block */
$helper = $block->getHelper();
?>
<?php if ($helper->getInfoConfig('enable') && $helper->getRichsnippetsConfig('custom')): ?>
<!-- Customizing Knowledge Graph by Mageplaza SEO-->
<!--Social Profiles, Business information -->
	<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Organization",
  "name" : "<?php echo $block->getBusinessName(); ?>",
  "url" : "<?php echo $block->getBaseUrl(); ?>",
  "logo": "<?php echo $block->getLogo(); ?>"
  <?php if ($block->getProfiles()): ?>
  ,"sameAs" : [<?php echo $block->getProfiles(); ?>
  ]
  <?php endif; ?>
  <?php if ($block->getBusinessPhone()): ?>
  ,"contactPoint" : [{
    "@type" : "ContactPoint",
    "telephone" : "<?php echo $block->getBusinessPhone(); ?>",
    "contactType" : "customer service"
  }]
  <?php endif; ?>
  <?php if ($block->getBusinessSalesPhone()): ?>
  ,"contactPoint" : [{
    "@type" : "ContactPoint",
    "telephone" : "<?php echo $block->getBusinessSalesPhone(); ?>",
    "contactType" : "sales"
  }]
  <?php endif; ?>
  <?php if ($block->getBusinessSupportPhone()): ?>
  ,"contactPoint" : [{
    "@type" : "ContactPoint",
    "telephone" : "<?php echo $block->getBusinessSupportPhone(); ?>",
    "contactType" : "technical support"
  }]
  <?php endif; ?>



}

    </script>

<?php endif; ?>
