<?php
/**
 * Learn more: https://developers.google.com/structured-data/rich-snippets/products#single_product_page
 */
?>

<?php if ($block->getProduct() && $block->getRichsnippetsHelper('enable_product')): ?>
    <?php $product = $block->getProduct(); ?>
    <!--    Product Rich Snippets by Mageplaza SEO-->
    <script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "<?php echo $product->getName(); ?>",
  "description": "<?php echo trim(strip_tags($product->getShortDescription())); ?>",
  <?php if ($product->getMpn()): ?>
  "mpn": "<?php echo $product->getMpn(); ?>",
  <?php endif; ?>
  "sku": "<?php echo $product->getSku(); ?>",
  "url": "<?php echo $product->getProductUrl(); ?>"
  <?php /*
  TO-DO: Allow select brand attribute in configuration > Get attribute label
  "brand": {
    "@type": "Thing",
    "name": "ACME"
  },
 */ ?>

 <?php if ($block->getReviewCount()): ?>
 ,
  "aggregateRating": {
    "@type": "AggregateRating",
    "bestRating": 100,
    "worstRating": 0,
    "ratingValue": "<?php echo $block->getRatingSummary(); ?>",
    "reviewCount": "<?php echo $block->getReviewCount(); ?>"
  }
  <?php endif; ?>

  <?php if ($product->getSpecialPrice() AND $product->getPrice() != $product->getSpecialPrice()): ?>
  ,
  "offers": {
    "@type": "Offer",
    "priceCurrency": "<?php echo $block->getCurrency(); ?>",
    "price": "<?php echo $product->getSpecialPrice(); ?>",
    "priceValidUntil": "<?php echo $product->getSpecialToDate(); ?>",
    "availability": "http://schema.org/InStock",
    <?php endif; ?>
  }
}

    </script>

<?php endif; ?>