<?php
/**
 * Learn more: https://developers.google.com/structured-data/rich-snippets/products#single_product_page
 */
/** @var \Mageplaza\Seo\Block\Richsnippets\Product $block */
?>
<?php if ($block->getProduct() && $block->getRichsnippetsHelper('enable_product') OR 1): ?>
	<?php $product = $block->getProduct(); ?>
	<!-- Product Structured Data by Mageplaza SEO-->
	<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "<?php echo $product->getName(); ?>",
  "image": "<?php echo $block->getUrl('pub/media/catalog') . 'product' . $product->getImage() ?>",
  "description": "<?php echo trim(strip_tags($product->getShortDescription())); ?>",
  <?php if ($product->getMpn()): ?>
  "mpn": "<?php echo $product->getMpn(); ?>",
  <?php endif; ?>
  "sku": "<?php echo $product->getSku(); ?>",
  <?php if ($label = $block->getBrandLabel()): ?>
  "brand": "<?php echo $label ?>",
  <?php endif; ?>
  "url": "<?php echo $product->getProductUrl(); ?>"

 <?php if ($block->getReviewCount()): ?>
 ,
  "aggregateRating": {
    "@type": "AggregateRating",
    "bestRating": 100,
    "worstRating": 0,
    "ratingValue": "<?php echo $block->getRatingSummary(); ?>",
    "reviewCount": "<?php echo $block->getReviewCount(); ?>"
  }
  <?php endif; ?>

  ,
  "offers": {
    "@type": "Offer",
    "priceCurrency": "<?php echo $block->getCurrency(); ?>",
    "price": "<?php echo $product->getPrice(); ?>",
    "priceValidUntil": "<?php echo $product->getSpecialToDate(); ?>",
    "itemOffered": "<?php echo $block->getQty($product->getId())?>",
    "availability": "http://schema.org/<?php echo ($block->isInStock($product->getId()) ? 'InStock' : 'OutOfStock') ?>"
  }
}

    </script>

<?php endif; ?>