<?php if ($block->getGoogleVerificationCode()): ?>
<!--Search engine verification by Mageplaza_SEO-->
	<meta name="google-site-verification" content="<?php echo $block->getGoogleVerificationCode() ?>">
<?php endif; ?>
<?php if ($block->getBingVerificationCode()): ?>
	<meta name="msvalidate.01" content="<?php echo $block->getBingVerificationCode() ?>">
<?php endif; ?>
<?php if ($block->getPinterestVerificationCode()): ?>
	<meta name="p:domain_verify" content="<?php echo $block->getPinterestVerificationCode(); ?>"/>
<?php endif; ?>
<?php if ($block->getYandexVerificationCode()): ?>
	<meta name="yandex-verification" content="<?php echo $block->getYandexVerificationCode(); ?>"/>
<?php endif; ?>
