<?php if ($block->getHelper()->getSocialShares('opengraph')): ?>
	<!--Open Graph Protocol for Facebook by Mageplaza_SEO-->
	<meta property="og:title" content="<?php echo $block->getStoreName() ?>"/>
	<meta property="og:type" content="website"/>
	<meta property="og:url" content="<?php echo $block->getStoreUrl(); ?>"/>
	<meta property="og:description" content="<?php echo $block->getStoreDescription(); ?>"/>
	<meta property="og:site_name" content="<?php echo $block->getBusinessName(); ?>"/>
<?php endif; ?>


<?php if ($block->getHelper()->getSocialShares('twitter_card') && $block->getHelper()->getSocialShares('twitter_account')): ?>
<!--	Twitter Card By Mageplaza_SEO-->
	<meta name="twitter:card" content="summary"/>
	<meta name="twitter:site" content="<?php echo $block->getTwitterAccount(); ?>"/>
	<meta name="twitter:title" content="<?php echo $block->getStoreName() ?>"/>
	<meta name="twitter:description" content="<?php echo $block->getStoreDescription(); ?>"/>
<?php endif; ?>

<?php if ($pinterest = $block->getHelper()->getSocialShares('pinterest')): ?>
<!--	Pinterest-->
	<meta name="p:domain_verify" content="<?php echo $pinterest; ?>"/>
<?php endif; ?>

<?php if ($googlePlus = $block->getHelper()->getSocialShares('google_plus')): ?>
<!--	Google Plus Publisher-->
	<link rel="publisher" href="<?php echo $googlePlus; ?>"/>
<?php endif; ?>
