<?php if ($product = $block->getRegistry('current_product')): ?>

	<?php if ($block->getHelper()->getSocialShares('opengraph')): ?>

		<!-- Open Graph Protocol by Mageplaza_SEO -->
		<meta property="og:type" content="product"/>
		<meta property="og:title" content="<?php echo $block->escapeHtml($product->getName()); ?>"/>
		<meta property="og:image" content="<?php echo $block->escapeUrl($block->getProductImage()); ?>" />
		<meta property="og:url" content="<?php echo $block->escapeUrl($block->getProduct()->getProductUrl()); ?>"/>
		<meta property="og:description" content="<?php echo $block->escapeHtml($block->getProduct()->getShortDescription()); ?>"/>
		<meta property="product:retailer_item_id" content="<?php echo $product->getSku() ?>"/>
		<meta property="og:site_name" content="<?php echo $block->getBusinessName(); ?>"/>
		<?php if ($priceAmount = $block->getProduct()->getFinalPrice()):?>
			<meta property="product:price:amount" content="<?php echo $priceAmount; ?>"/>
			<?php echo $block->getChildHtml('meta.currency'); ?>
		<?php endif;?>

	<?php endif; ?>

	<?php if ($block->getHelper()->getSocialShares('twitter_card') && $block->getHelper()->getSocialShares('twitter_account')): ?>
		<!--	Twitter Card By Mageplaza SEO-->
		<meta name="twitter:card" content="summary"/>
		<meta name="twitter:site" content="<?php echo $block->escapeHtml($block->getTwitterAccount()); ?>"/>
		<meta name="twitter:title" content="<?php echo $block->escapeHtml($product->getName()); ?>"/>
		<meta name="twitter:description" content="<?php echo $block->escapeHtml($block->getProduct()->getShortDescription()); ?>"/>
		<meta name="twitter:image" content="<?php echo $block->escapeUrl($block->getProductImage()); ?>"/>
	<?php endif; ?>


	<?php if ($pinterest = $block->getHelper()->getSocialShares('pinterest')): ?>
		<meta name="p:domain_verify" content="<?php echo $pinterest; ?>"/>
	<?php endif; ?>

	<?php if ($googlePlus = $block->getHelper()->getSocialShares('google_plus')): ?>
		<link rel="publisher" href="<?php echo $googlePlus; ?>" />
	<?php endif; ?>

<?php endif; ?>