<!--Open Graph Protocol for Facebook by Mageplaza SEO-->
<?php if ($category = Mage::registry('current_category')): ?>
	<meta property="og:title" content="<?php echo $category->getName() ?>"/>
	<meta property="og:type" content="product.group"/>
	<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>"/>
	<?php if ($category->getShortDescription()): ?>
		<meta property="og:description" content="<?php echo trim(strip_tags($category->getDescription())) ?>"/>
	<?php endif; ?>
	
	<meta property="og:site_name" content="<?php echo $this->getBusinessName();?>"/>

	<!--	Twitter Card By Mageplaza SEO-->
	<meta name="twitter:card" content="summary"/>
	<meta name="twitter:site" content="<?php echo $this->getTwitterAccount(); ?>"/>
	<meta name="twitter:title" content="<?php echo $category->getName() ?>"/>
	<?php if ($category->getShortDescription()): ?>
		<meta name="twitter:description" content="<?php echo trim(strip_tags($category->getDescription())); ?>"/>
	<?php endif; ?>
<?php endif; ?>