<?php
/**
 * Learn more: https://developers.google.com/structured-data/rich-snippets/products#single_product_page
 */
?>
<?php if(Mage::registry('current_product')): ?>
<?php $product = Mage::registry('current_product'); ?>
<!--    Product Rich Snippets by Mageplaza SEO-->
<script type="application/ld+json">
{
  "@context": "http://schema.org/",
  "@type": "Product",
  "name": "<?php echo $product->getName();?>",
  "image": "<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(200,200);?>",
  "description": "<?php echo trim(strip_tags($product->getShortDescription())); ?>",
  <?php if($product->getMpn()):?>
  "mpn": "<?php echo $product->getMpn();?>",
  <?php endif; ?>
  "sku": "<?php echo $product->getSku();?>",
  "url": "<?php echo $product->getProductUrl();?>",
  <?php /*
  TO-DO: Allow select brand attribute in configuration > Get attribute label
  "brand": {
    "@type": "Thing",
    "name": "ACME"
  },
 */?>

 <?php if($this->getReviewCount()):?>
  "aggregateRating": {
    "@type": "AggregateRating",
    "ratingValue": "<?php echo $this->getRatingSummary();?>",
    "reviewCount": "<?php echo $this->getReviewCount();?>"
  },
  <?php endif;?>

  <?php if($product->getSpecialPrice() AND $product->getPrice() != $product->getSpecialPrice()):?>
  "offers": {
    "@type": "Offer",
    "priceCurrency": "<?php echo $this->getCurrency();?>",
    "price": "<?php echo $product->getSpecialPrice();?>",
    "priceValidUntil": "<?php echo $product->getSpecialToDate();?>",
    "availability": "http://schema.org/InStock",
    <?php endif; ?>
  }
}
</script>

<?php endif; ?>