aaaaaaaaaaaaaaaa
<!--<script type="application/ld+json">-->
<!--{-->
<!--  "@context": "http://schema.org",-->
<!--  "@type": "WebSite",-->
<!--  "url": "--><?php //echo Mage::getBaseUrl(true) ?><!--",-->
<!--  "potentialAction": {-->
<!--    "@type": "SearchAction",-->
<!--    "target": "--><?php //echo Mage::getBaseUrl(true) ?><!--catalogsearch/result/q={search_term_string}",-->
<!--    --><?php //if($this->getSitelinksApp()):?>
<!--	"target": "android-app://--><?php //echo $this->getSitelinksAppCode();?><!--/--><?php //echo $this->getSiteLinkDomainForApp();?><!--catalogsearch/result/?q={search_term}"-->
<!--    --><?php //endif;?>
<!--    "query-input": "required name=search_term_string"-->
<!--  }-->
<!--}-->
<!--</script>-->
